package sub

// Differentiated Services Field Codepoints (DSCP), Updated: 2018-05-04
const (
	IANA_DiffServCS0           = 0x00 // CS0
	IANA_DiffServCS1           = 0x20 // CS1
	IANA_DiffServCS2           = 0x40 // CS2
	IANA_DiffServCS3           = 0x60 // CS3
	IANA_DiffServCS4           = 0x80 // CS4
	IANA_DiffServCS5           = 0xa0 // CS5
	IANA_DiffServCS6           = 0xc0 // CS6
	IANA_DiffServCS7           = 0xe0 // CS7
	IANA_DiffServAF11          = 0x28 // AF11
	IANA_DiffServAF12          = 0x30 // AF12
	IANA_DiffServAF13          = 0x38 // AF13
	IANA_DiffServAF21          = 0x48 // AF21
	IANA_DiffServAF22          = 0x50 // AF22
	IANA_DiffServAF23          = 0x58 // AF23
	IANA_DiffServAF31          = 0x68 // AF31
	IANA_DiffServAF32          = 0x70 // AF32
	IANA_DiffServAF33          = 0x78 // AF33
	IANA_DiffServAF41          = 0x88 // AF41
	IANA_DiffServAF42          = 0x90 // AF42
	IANA_DiffServAF43          = 0x98 // AF43
	IANA_DiffServEF            = 0xb8 // EF
	IANA_DiffServVOICEADMIT    = 0xb0 // VOICE-ADMIT
	IANA_NotECNTransport       = 0x00 // Not-ECT (Not ECN-Capable Transport)
	IANA_ECNTransport1         = 0x01 // ECT(1) (ECN-Capable Transport(1))
	IANA_ECNTransport0         = 0x02 // ECT(0) (ECN-Capable Transport(0))
	IANA_CongestionExperienced = 0x03 // CE (Congestion Experienced)
)

// Protocol Numbers, Updated: 2017-10-13
const (
	IANA_ProtocolIP             = 0   // IPv4 encapsulation, pseudo protocol number
	IANA_ProtocolHOPOPT         = 0   // IPv6 Hop-by-Hop Option
	IANA_ProtocolICMP           = 1   // Internet Control Message
	IANA_ProtocolIGMP           = 2   // Internet Group Management
	IANA_ProtocolGGP            = 3   // Gateway-to-Gateway
	IANA_ProtocolIPv4           = 4   // IPv4 encapsulation
	IANA_ProtocolST             = 5   // Stream
	IANA_ProtocolTCP            = 6   // Transmission Control
	IANA_ProtocolCBT            = 7   // CBT
	IANA_ProtocolEGP            = 8   // Exterior Gateway Protocol
	IANA_ProtocolIGP            = 9   // any private interior gateway (used by Cisco for their IGRP)
	IANA_ProtocolBBNRCCMON      = 10  // BBN RCC Monitoring
	IANA_ProtocolNVPII          = 11  // Network Voice Protocol
	IANA_ProtocolPUP            = 12  // PUP
	IANA_ProtocolEMCON          = 14  // EMCON
	IANA_ProtocolXNET           = 15  // Cross Net Debugger
	IANA_ProtocolCHAOS          = 16  // Chaos
	IANA_ProtocolUDP            = 17  // User Datagram
	IANA_ProtocolMUX            = 18  // Multiplexing
	IANA_ProtocolDCNMEAS        = 19  // DCN Measurement Subsystems
	IANA_ProtocolHMP            = 20  // Host Monitoring
	IANA_ProtocolPRM            = 21  // Packet Radio Measurement
	IANA_ProtocolXNSIDP         = 22  // XEROX NS IDP
	IANA_ProtocolTRUNK1         = 23  // Trunk-1
	IANA_ProtocolTRUNK2         = 24  // Trunk-2
	IANA_ProtocolLEAF1          = 25  // Leaf-1
	IANA_ProtocolLEAF2          = 26  // Leaf-2
	IANA_ProtocolRDP            = 27  // Reliable Data Protocol
	IANA_ProtocolIRTP           = 28  // Internet Reliable Transaction
	IANA_ProtocolISOTP4         = 29  // ISO Transport Protocol Class 4
	IANA_ProtocolNETBLT         = 30  // Bulk Data Transfer Protocol
	IANA_ProtocolMFENSP         = 31  // MFE Network Services Protocol
	IANA_ProtocolMERITINP       = 32  // MERIT Internodal Protocol
	IANA_ProtocolDCCP           = 33  // Datagram Congestion Control Protocol
	IANA_Protocol3PC            = 34  // Third Party Connect Protocol
	IANA_ProtocolIDPR           = 35  // Inter-Domain Policy Routing Protocol
	IANA_ProtocolXTP            = 36  // XTP
	IANA_ProtocolDDP            = 37  // Datagram Delivery Protocol
	IANA_ProtocolIDPRCMTP       = 38  // IDPR Control Message Transport Proto
	IANA_ProtocolTPPP           = 39  // TP++ Transport Protocol
	IANA_ProtocolIL             = 40  // IL Transport Protocol
	IANA_ProtocolIPv6           = 41  // IPv6 encapsulation
	IANA_ProtocolSDRP           = 42  // Source Demand Routing Protocol
	IANA_ProtocolIPv6Route      = 43  // Routing Header for IPv6
	IANA_ProtocolIPv6Frag       = 44  // Fragment Header for IPv6
	IANA_ProtocolIDRP           = 45  // Inter-Domain Routing Protocol
	IANA_ProtocolRSVP           = 46  // Reservation Protocol
	IANA_ProtocolGRE            = 47  // Generic Routing Encapsulation
	IANA_ProtocolDSR            = 48  // Dynamic Source Routing Protocol
	IANA_ProtocolBNA            = 49  // BNA
	IANA_ProtocolESP            = 50  // Encap Security Payload
	IANA_ProtocolAH             = 51  // Authentication Header
	IANA_ProtocolINLSP          = 52  // Integrated Net Layer Security  TUBA
	IANA_ProtocolNARP           = 54  // NBMA Address Resolution Protocol
	IANA_ProtocolMOBILE         = 55  // IP Mobility
	IANA_ProtocolTLSP           = 56  // Transport Layer Security Protocol using Kryptonet key management
	IANA_ProtocolSKIP           = 57  // SKIP
	IANA_ProtocolIPv6ICMP       = 58  // ICMP for IPv6
	IANA_ProtocolIPv6NoNxt      = 59  // No Next Header for IPv6
	IANA_ProtocolIPv6Opts       = 60  // Destination Options for IPv6
	IANA_ProtocolCFTP           = 62  // CFTP
	IANA_ProtocolSATEXPAK       = 64  // SATNET and Backroom EXPAK
	IANA_ProtocolKRYPTOLAN      = 65  // Kryptolan
	IANA_ProtocolRVD            = 66  // MIT Remote Virtual Disk Protocol
	IANA_ProtocolIPPC           = 67  // Internet Pluribus Packet Core
	IANA_ProtocolSATMON         = 69  // SATNET Monitoring
	IANA_ProtocolVISA           = 70  // VISA Protocol
	IANA_ProtocolIPCV           = 71  // Internet Packet Core Utility
	IANA_ProtocolCPNX           = 72  // Computer Protocol Network Executive
	IANA_ProtocolCPHB           = 73  // Computer Protocol Heart Beat
	IANA_ProtocolWSN            = 74  // Wang Span Network
	IANA_ProtocolPVP            = 75  // Packet Video Protocol
	IANA_ProtocolBRSATMON       = 76  // Backroom SATNET Monitoring
	IANA_ProtocolSUNND          = 77  // SUN ND PROTOCOL-Temporary
	IANA_ProtocolWBMON          = 78  // WIDEBAND Monitoring
	IANA_ProtocolWBEXPAK        = 79  // WIDEBAND EXPAK
	IANA_ProtocolISOIP          = 80  // ISO Internet Protocol
	IANA_ProtocolVMTP           = 81  // VMTP
	IANA_ProtocolSECUREVMTP     = 82  // SECURE-VMTP
	IANA_ProtocolVINES          = 83  // VINES
	IANA_ProtocolTTP            = 84  // Transaction Transport Protocol
	IANA_ProtocolIPTM           = 84  // Internet Protocol Traffic Manager
	IANA_ProtocolNSFNETIGP      = 85  // NSFNET-IGP
	IANA_ProtocolDGP            = 86  // Dissimilar Gateway Protocol
	IANA_ProtocolTCF            = 87  // TCF
	IANA_ProtocolEIGRP          = 88  // EIGRP
	IANA_ProtocolOSPFIGP        = 89  // OSPFIGP
	IANA_ProtocolSpriteRPC      = 90  // Sprite RPC Protocol
	IANA_ProtocolLARP           = 91  // Locus Address Resolution Protocol
	IANA_ProtocolMTP            = 92  // Multicast Transport Protocol
	IANA_ProtocolAX25           = 93  // AX.25 Frames
	IANA_ProtocolIPIP           = 94  // IP-within-IP Encapsulation Protocol
	IANA_ProtocolSCCSP          = 96  // Semaphore Communications Sec. Pro.
	IANA_ProtocolETHERIP        = 97  // Ethernet-within-IP Encapsulation
	IANA_ProtocolENCAP          = 98  // Encapsulation Header
	IANA_ProtocolGMTP           = 100 // GMTP
	IANA_ProtocolIFMP           = 101 // Ipsilon Flow Management Protocol
	IANA_ProtocolPNNI           = 102 // PNNI over IP
	IANA_ProtocolPIM            = 103 // Protocol Independent Multicast
	IANA_ProtocolARIS           = 104 // ARIS
	IANA_ProtocolSCPS           = 105 // SCPS
	IANA_ProtocolQNX            = 106 // QNX
	IANA_ProtocolAN             = 107 // Active Networks
	IANA_ProtocolIPComp         = 108 // IP Payload Compression Protocol
	IANA_ProtocolSNP            = 109 // Sitara Networks Protocol
	IANA_ProtocolCompaqPeer     = 110 // Compaq Peer Protocol
	IANA_ProtocolIPXinIP        = 111 // IPX in IP
	IANA_ProtocolVRRP           = 112 // Virtual Router Redundancy Protocol
	IANA_ProtocolPGM            = 113 // PGM Reliable Transport Protocol
	IANA_ProtocolL2TP           = 115 // Layer Two Tunneling Protocol
	IANA_ProtocolDDX            = 116 // D-II Data Exchange (DDX)
	IANA_ProtocolIATP           = 117 // Interactive Agent Transfer Protocol
	IANA_ProtocolSTP            = 118 // Schedule Transfer Protocol
	IANA_ProtocolSRP            = 119 // SpectraLink Radio Protocol
	IANA_ProtocolUTI            = 120 // UTI
	IANA_ProtocolSMP            = 121 // Simple Message Protocol
	IANA_ProtocolPTP            = 123 // Performance Transparency Protocol
	IANA_ProtocolISIS           = 124 // ISIS over IPv4
	IANA_ProtocolFIRE           = 125 // FIRE
	IANA_ProtocolCRTP           = 126 // Combat Radio Transport Protocol
	IANA_ProtocolCRUDP          = 127 // Combat Radio User Datagram
	IANA_ProtocolSSCOPMCE       = 128 // SSCOPMCE
	IANA_ProtocolIPLT           = 129 // IPLT
	IANA_ProtocolSPS            = 130 // Secure Packet Shield
	IANA_ProtocolPIPE           = 131 // Private IP Encapsulation within IP
	IANA_ProtocolSCTP           = 132 // Stream Control Transmission Protocol
	IANA_ProtocolFC             = 133 // Fibre Channel
	IANA_ProtocolRSVPE2EIGNORE  = 134 // RSVP-E2E-IGNORE
	IANA_ProtocolMobilityHeader = 135 // Mobility Header
	IANA_ProtocolUDPLite        = 136 // UDPLite
	IANA_ProtocolMPLSinIP       = 137 // MPLS-in-IP
	IANA_ProtocolMANET          = 138 // MANET Protocols
	IANA_ProtocolHIP            = 139 // Host Identity Protocol
	IANA_ProtocolShim6          = 140 // Shim6 Protocol
	IANA_ProtocolWESP           = 141 // Wrapped Encapsulating Security Payload
	IANA_ProtocolROHC           = 142 // Robust Header Compression
	IANA_ProtocolReserved       = 255 // Reserved
)

// Address Family Numbers, Updated: 2018-04-02
const (
	IANA_AddrFamilyIPv4                          = 1     // IP (IP version 4)
	IANA_AddrFamilyIPv6                          = 2     // IP6 (IP version 6)
	IANA_AddrFamilyNSAP                          = 3     // NSAP
	IANA_AddrFamilyHDLC                          = 4     // HDLC (8-bit multidrop)
	IANA_AddrFamilyBBN1822                       = 5     // BBN 1822
	IANA_AddrFamily802                           = 6     // 802 (includes all 802 media plus Ethernet "canonical format")
	IANA_AddrFamilyE163                          = 7     // E.163
	IANA_AddrFamilyE164                          = 8     // E.164 (SMDS, Frame Relay, ATM)
	IANA_AddrFamilyF69                           = 9     // F.69 (Telex)
	IANA_AddrFamilyX121                          = 10    // X.121 (X.25, Frame Relay)
	IANA_AddrFamilyIPX                           = 11    // IPX
	IANA_AddrFamilyAppletalk                     = 12    // Appletalk
	IANA_AddrFamilyDecnetIV                      = 13    // Decnet IV
	IANA_AddrFamilyBanyanVines                   = 14    // Banyan Vines
	IANA_AddrFamilyE164withSubaddress            = 15    // E.164 with NSAP format subaddress
	IANA_AddrFamilyDNS                           = 16    // DNS (Domain Name System)
	IANA_AddrFamilyDistinguishedName             = 17    // Distinguished Name
	IANA_AddrFamilyASNumber                      = 18    // AS Number
	IANA_AddrFamilyXTPoverIPv4                   = 19    // XTP over IP version 4
	IANA_AddrFamilyXTPoverIPv6                   = 20    // XTP over IP version 6
	IANA_AddrFamilyXTPnativemodeXTP              = 21    // XTP native mode XTP
	IANA_AddrFamilyFibreChannelWorldWidePortName = 22    // Fibre Channel World-Wide Port Name
	IANA_AddrFamilyFibreChannelWorldWideNodeName = 23    // Fibre Channel World-Wide Node Name
	IANA_AddrFamilyGWID                          = 24    // GWID
	IANA_AddrFamilyL2VPN                         = 25    // AFI for L2VPN information
	IANA_AddrFamilyMPLSTPSectionEndpointID       = 26    // MPLS-TP Section Endpoint Identifier
	IANA_AddrFamilyMPLSTPLSPEndpointID           = 27    // MPLS-TP LSP Endpoint Identifier
	IANA_AddrFamilyMPLSTPPseudowireEndpointID    = 28    // MPLS-TP Pseudowire Endpoint Identifier
	IANA_AddrFamilyMTIPv4                        = 29    // MT IP: Multi-Topology IP version 4
	IANA_AddrFamilyMTIPv6                        = 30    // MT IPv6: Multi-Topology IP version 6
	IANA_AddrFamilyEIGRPCommonServiceFamily      = 16384 // EIGRP Common Service Family
	IANA_AddrFamilyEIGRPIPv4ServiceFamily        = 16385 // EIGRP IPv4 Service Family
	IANA_AddrFamilyEIGRPIPv6ServiceFamily        = 16386 // EIGRP IPv6 Service Family
	IANA_AddrFamilyLISPCanonicalAddressFormat    = 16387 // LISP Canonical Address Format (LCAF)
	IANA_AddrFamilyBGPLS                         = 16388 // BGP-LS
	IANA_AddrFamily48bitMAC                      = 16389 // 48-bit MAC
	IANA_AddrFamily64bitMAC                      = 16390 // 64-bit MAC
	IANA_AddrFamilyOUI                           = 16391 // OUI
	IANA_AddrFamilyMACFinal24bits                = 16392 // MAC/24
	IANA_AddrFamilyMACFinal40bits                = 16393 // MAC/40
	IANA_AddrFamilyIPv6Initial64bits             = 16394 // IPv6/64
	IANA_AddrFamilyRBridgePortID                 = 16395 // RBridge Port ID
	IANA_AddrFamilyTRILLNickname                 = 16396 // TRILL Nickname
)
